---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseURL: "http://svett-ifi.github.io/"
title: "Svett@ifi Blogg"
theme: "redlounge"
canonifyurls: true
config: "config.yaml"
metaDataFormat: "yaml"
params:
  sidebartitle  : Svett
  sidebartagline: studentforening p√• ifi
  sidebarphoto  : '/images/logo.png'
...
